pipeline:
  name: nextjs-demo-repo
  identifier: nextjsdemorepo
  projectIdentifier: Jan_Schulte
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: JS_GitHub
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8sbuilder
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Install
                  identifier: Install
                  spec:
                    connectorRef: account.harnessImage
                    image: docker.io/node:22-alpine3.19
                    shell: Sh
                    command: npm ci
              - step:
                  name: Test
                  identifier: Build
                  template:
                    templateRef: npmtest
                    versionLabel: "1"
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: JS_Docker_Registry
                    repo: schultejan/nextjsblog
                    tags:
                      - latest
                    resources:
                      limits:
                        memory: 2G
    - stage:
        name: Code Scanning
        identifier: Code_Scanning
        description: ""
        type: SecurityTests
        spec:
          cloneCodebase: true
          infrastructure:
            useFromStage: Build
          execution:
            steps:
              - step:
                  type: AquaTrivy
                  name: AquaTrivy
                  identifier: AquaTrivy
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: container
                      detection: auto
                    advanced:
                      log:
                        level: info
                      fail_on_severity: high
                    privileged: true
                    image:
                      type: docker_v2
                      name: schultejan/nextjsblog
                      tag: latest
    - stage:
        name: deploy-nextjsblog
        identifier: deploynextjsblog
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: nextjsblog
          environment:
            environmentRef: harnessdevenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: minikubeinfra
          execution:
            steps:
              - stepGroup:
                  name: Canary Deployment
                  identifier: canaryDepoyment
                  steps:
                    - step:
                        name: Canary Deployment
                        identifier: canaryDeployment
                        type: K8sCanaryDeploy
                        timeout: 10m
                        spec:
                          instanceSelection:
                            type: Count
                            spec:
                              count: 1
                          skipDryRun: false
                    - step:
                        name: Canary Delete
                        identifier: canaryDelete
                        type: K8sCanaryDelete
                        timeout: 10m
                        spec: {}
              - stepGroup:
                  name: Primary Deployment
                  identifier: primaryDepoyment
                  steps:
                    - step:
                        name: Rolling Deployment
                        identifier: rollingDeployment
                        type: K8sRollingDeploy
                        timeout: 10m
                        spec:
                          skipDryRun: false
            rollbackSteps:
              - step:
                  name: Canary Delete
                  identifier: rollbackCanaryDelete
                  type: K8sCanaryDelete
                  timeout: 10m
                  spec: {}
              - step:
                  name: Rolling Rollback
                  identifier: rollingRollback
                  type: K8sRollingRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
