apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-blog
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nextjs-blog
  template:
    metadata:
      labels:
        app: nextjs-blog
    spec:
      containers:
        - image: schultejan/nextjsblog
          imagePullPolicy: IfNotPresent
          name: nextjs-blog
          ports:
            - containerPort: 80
